# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/fu6315ma-s/Lab4/Lab4.cache/wt [current_project]
set_property parent.project_path C:/Users/fu6315ma-s/Lab4/Lab4.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part digilentinc.com:nexys4:part0:1.1 [current_project]
add_files C:/Users/fu6315ma-s/Lab4/Lab4.srcs/sim_1/imports/Lab4/welcome_480x120.coe
read_vhdl -library xil_defaultlib {
  C:/Users/fu6315ma-s/Lab4/Lab4.srcs/sources_1/imports/Lab4/sync_keyboard.vhd
  C:/Users/fu6315ma-s/Lab4/Lab4.srcs/sources_1/imports/Lab4/keyboard_ctrl.vhd
  C:/Users/fu6315ma-s/Lab4/Lab4.srcs/sources_1/imports/Lab4/convert_to_binary.vhd
  C:/Users/fu6315ma-s/Lab4/Lab4.srcs/sources_1/imports/Lab4/convert_scancode.vhd
  C:/Users/fu6315ma-s/Lab4/Lab4.srcs/sources_1/imports/Lab4/ALU_components.vhd
  C:/Users/fu6315ma-s/Lab4/Lab4.srcs/sources_1/imports/Lab4/7SegDriver.vhd
  C:/Users/fu6315ma-s/Lab4/Lab4.srcs/sources_1/new/keyboard.vhd
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/fu6315ma-s/Lab4/Lab4.srcs/constrs_1/imports/Downloads/Nexys4Master.xdc
set_property used_in_implementation false [get_files C:/Users/fu6315ma-s/Lab4/Lab4.srcs/constrs_1/imports/Downloads/Nexys4Master.xdc]


synth_design -top keyboard -part xc7a100tcsg324-1


write_checkpoint -force -noxdef keyboard.dcp

catch { report_utilization -file keyboard_utilization_synth.rpt -pb keyboard_utilization_synth.pb }
