# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/fu6315ma-s/Lab4/Lab4.cache/wt [current_project]
set_property parent.project_path C:/Users/fu6315ma-s/Lab4/Lab4.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part digilentinc.com:nexys4:part0:1.1 [current_project]
add_files C:/Users/fu6315ma-s/Lab4/Lab4.srcs/sim_1/imports/Lab4/welcome_480x120.coe
add_files -quiet c:/Users/fu6315ma-s/Lab4/Lab4.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.dcp
set_property used_in_implementation false [get_files c:/Users/fu6315ma-s/Lab4/Lab4.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.dcp]
read_vhdl -library xil_defaultlib {
  C:/Users/fu6315ma-s/Lab4/Lab4.srcs/sources_1/imports/Lab4/vga_controller_640_60.vhd
  C:/Users/fu6315ma-s/Lab4/Lab4.srcs/sources_1/new/seven_seg_dig.vhd
  C:/Users/fu6315ma-s/Lab4/Lab4.srcs/sources_1/new/7seg_vga.vhd
  C:/Users/fu6315ma-s/Lab4/Lab4.srcs/sources_1/imports/Lab4/vga_ref_pack.vhd
  C:/Users/fu6315ma-s/Lab4/Lab4.srcs/sources_1/imports/Lab4/vga_ref.vhd
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/fu6315ma-s/Lab4/Lab4.srcs/constrs_1/imports/new/vga_constraints.xdc
set_property used_in_implementation false [get_files C:/Users/fu6315ma-s/Lab4/Lab4.srcs/constrs_1/imports/new/vga_constraints.xdc]


synth_design -top vga_ref -part xc7a100tcsg324-1


write_checkpoint -force -noxdef vga_ref.dcp

catch { report_utilization -file vga_ref_utilization_synth.rpt -pb vga_ref_utilization_synth.pb }
