# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/fu6315ma-s/eitf35-lab4/Lab4.srcs/sources_1/ip/ram_8kB/ram_8kB.xci
# IP: The module: 'ram_8kB' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/fu6315ma-s/eitf35-lab4/Lab4.srcs/sources_1/ip/ram_8kB/ram_8kB_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ram_8kB'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: C:/Users/fu6315ma-s/eitf35-lab4/Lab4.srcs/sources_1/ip/ram_8kB/ram_8kB.xci
# IP: The module: 'ram_8kB' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/fu6315ma-s/eitf35-lab4/Lab4.srcs/sources_1/ip/ram_8kB/ram_8kB_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ram_8kB'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
